from 172.168.1.10:30006/common/openjdk8
workdir /
copy ./deploy/config /config
copy ./target/fmaking-0.0.1-SNAPSHOT.jar /fmaking-0.0.1-SNAPSHOT.jar
copy ./startup.sh /startup.sh
run chmod 755 /startup.sh
entrypoint ["/startup.sh"]
