FROM 172.168.1.10:30006/common/openjdk8:latest
workdir /
copy ./deploy/config /config
copy ./target/newWorkflow-0.0.1-SNAPSHOT.jar /newWorkflow-0.0.1-SNAPSHOT.jar
copy ./startup.sh /startup.sh
run chmod 755 /startup.sh
run ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
entrypoint ["/startup.sh"]
